language: csharp
solution: src/RunProcessAsTask.sln
mono: none
dotnet: 2.0.0
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.1.0
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

script:
  - cd src
  - dotnet build
  - cd RunProcessAsTask.Tests
  - dotnet test
  - cd ../..
