version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  matrix:
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
before_build:
  - nuget restore ".\src\RunProcessAsTask.sln"
build:
  project: .\src\RunProcessAsTask.sln
  verbosity: minimal
test_script:
- ps: >-
    $xunit              = (Resolve-Path "src/packages/xunit.runner.console.*/tools/xunit.console.exe").ToString()
    
    $opencover          = (Resolve-Path ".\src\packages\OpenCover.*\tools\OpenCover.Console.exe").ToString()
    
    $coveralls          = (Resolve-Path "src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $assemblies         = (Resolve-Path "src\RunProcessAsTask.Tests\bin\$env:CONFIGURATION\RunProcessAsTask.Tests.dll").ToString()
    
    $filters            = "+[RunProcessAsTask*]*"
    
    & $opencover "-register:user" "-target:$xunit" "-targetargs:$assemblies -noshadow -appveyor" "-filter:$filters" "-output:opencoverCoverage.xml"
    

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
