version: 1.0.{build}
skip_tags: true
configuration: Release
environment:
  matrix:
  - platform: Any CPU
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
before_build:
  - dotnet restore ".\src\RunProcessAsTask.sln"
build:
  project: .\src\RunProcessAsTask.sln
  verbosity: minimal
test_script:
  - pushd src\RunProcessAsTask.Tests
  - dotnet test
  - popd
